name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
     
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup script
        working-directory: ./backend
        run: |
          echo "python -m gunicorn application:app --bind=0.0.0.0:8000 --timeout=600" > startup.sh
          chmod +x startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uaf-cgpa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "PYTHON|3.9" \
              --startup-file "startup.sh"

            az webapp config appsettings set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --settings \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                WEBSITES_PORT=8000 \
                PORT=8000

            az webapp restart --name uaf-cgpa-api --resource-group uaf-cgpa-rg

