name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
     
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "DEBUG=False" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=8000" >> .env
          echo "ENVIRONMENT=production" >> .env
          echo "BROWSER_TYPE=chrome" >> .env
          echo "CHROME_BINARY_PATH=/usr/bin/google-chrome" >> .env
          echo "DRIVER_CACHE_PATH=/tmp/webdriver" >> .env
          echo "WDM_LOG_LEVEL=20" >> .env
          echo "WDM_LOCAL=1" >> .env
          echo "WDM_SSL_VERIFY=1" >> .env
          echo "CHROME_TIMEOUT=30" >> .env

      - name: Create startup.sh
        working-directory: ./backend
        run: |
          echo '#!/bin/bash' > startup.sh
          echo 'cd /home/site/wwwroot' >> startup.sh
          echo 'curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' >> startup.sh
          echo 'apt-get update && apt-get install -y ./google-chrome-stable_current_amd64.deb' >> startup.sh
          echo 'gunicorn --bind=0.0.0.0:8000 --timeout 600 application:app' >> startup.sh
          chmod +x startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uaf-cgpa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
          startup-command: 'sh /home/site/wwwroot/startup.sh'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "PYTHON|3.9"

            az webapp config appsettings set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --settings \
                WEBSITES_PORT=8000 \
                BROWSER_TYPE=chrome \
                CHROME_BINARY_PATH=/usr/bin/google-chrome \
                DRIVER_CACHE_PATH=/tmp/webdriver \
                WDM_LOG_LEVEL=20 \
                CHROME_TIMEOUT=30 \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true

            az webapp stop --name uaf-cgpa-api --resource-group uaf-cgpa-rg
            az webapp start --name uaf-cgpa-api --resource-group uaf-cgpa-rg

