name: Deploy Backend API

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

env:
  AZURE_WEBAPP_NAME: 'uaf-cgpa-api'
  CONTAINER_REGISTRY: 'uafcgparegistry'
  DOCKER_CONTEXT_PATH: './backend'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_CONTEXT_PATH }}
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/cgpa-api:${{ github.sha }}
          build-args: |
            PORT=8000
            DEBUG=False
            ENVIRONMENT=production

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/cgpa-api:${{ github.sha }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group uaf-cgpa-rg \
              --settings \
                WEBSITES_PORT=8000 \
                DEBUG=False \
                ENVIRONMENT=production \
                WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
                DOCKER_ENABLE_CI=true \
                DOCKER_REGISTRY_SERVER_URL="https://${{ env.CONTAINER_REGISTRY }}.azurecr.io" \
                DOCKER_REGISTRY_SERVER_USERNAME="${{ secrets.ACR_USERNAME }}" \
                DOCKER_REGISTRY_SERVER_PASSWORD="${{ secrets.ACR_PASSWORD }}"

            az webapp restart \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group uaf-cgpa-rg
