name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
     
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "DEBUG=False" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=8000" >> .env
          echo "ENVIRONMENT=production" >> .env
          echo "BROWSER_TYPE=chrome" >> .env
          echo "CHROME_TIMEOUT=30" >> .env

      - name: Create gunicorn.conf.py
        working-directory: ./backend
        run: |
          echo "bind = '0.0.0.0:8000'" > gunicorn.conf.py
          echo "workers = 4" >> gunicorn.conf.py
          echo "timeout = 600" >> gunicorn.conf.py
          echo "accesslog = '-'" >> gunicorn.conf.py
          echo "errorlog = '-'" >> gunicorn.conf.py

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uaf-cgpa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Configure basic settings
            az webapp config set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "PYTHON|3.9" \
              --always-on true

            # Configure app settings
            az webapp config appsettings set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --settings \
                WEBSITES_PORT=8000 \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true \
                GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000 --workers=4 --timeout=600 --access-logfile - --error-logfile - --config gunicorn.conf.py" \
                FLASK_APP=application.py

            # Restart the web app
            az webapp restart --name uaf-cgpa-api --resource-group uaf-cgpa-rg

