name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
     
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment files
        working-directory: ./backend
        run: |
          # Create startup file
          echo "cd /home/site/wwwroot && gunicorn --bind=0.0.0.0:8000 --timeout=600 wsgi:app" > startup.sh
          chmod +x startup.sh

          # Create web.config
          echo '<?xml version="1.0" encoding="utf-8"?>' > web.config
          echo '<configuration>' >> web.config
          echo '  <system.webServer>' >> web.config
          echo '    <handlers>' >> web.config
          echo '      <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>' >> web.config
          echo '    </handlers>' >> web.config
          echo '    <httpPlatform processPath="%HOME%\site\wwwroot\env\Scripts\python.exe"' >> web.config
          echo '                  arguments="-m gunicorn wsgi:app --bind 0.0.0.0:8000"' >> web.config
          echo '                  stdoutLogEnabled="true"' >> web.config
          echo '                  stdoutLogFile="%HOME%\LogFiles\python.log">' >> web.config
          echo '      <environmentVariables>' >> web.config
          echo '        <environmentVariable name="PYTHONPATH" value="%HOME%\site\wwwroot"/>' >> web.config
          echo '      </environmentVariables>' >> web.config
          echo '    </httpPlatform>' >> web.config
          echo '  </system.webServer>' >> web.config
          echo '</configuration>' >> web.config

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uaf-cgpa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "PYTHON|3.9" \
              --always-on true

            az webapp config appsettings set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --settings \
                WEBSITES_PORT=8000 \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true \
                PYTHON_PATH="/home/site/wwwroot" \
                PYTHONPATH="/home/site/wwwroot" \
                PORT=8000 \
                FLASK_APP="wsgi.py"

            az webapp restart --name uaf-cgpa-api --resource-group uaf-cgpa-rg

