name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "DEBUG=False" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=8000" >> .env
          echo "CACHE_TIMEOUT=3600" >> .env
          echo "SCRAPER_TIMEOUT=20" >> .env
          echo "CHROME_TIMEOUT=10" >> .env

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'uaf-cgpa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "PYTHON|3.9"
            
            az webapp config appsettings set \
              --name uaf-cgpa-api \
              --resource-group uaf-cgpa-rg \
              --settings \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true \
                DEBUG=False \
                HOST=0.0.0.0 \
                PORT=8000
