name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'cgpa-calculator/**'

env:
  NODE_VERSION: '18'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: cgpa-calculator/package-lock.json

      - name: Install Dependencies
        working-directory: ./cgpa-calculator
        run: npm ci

      - name: Build Application
        working-directory: ./cgpa-calculator
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.AZURE_API_URL }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "cgpa-calculator"
          output_location: "out"
          skip_app_build: true
