name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'cgpa-calculator/**'

env:
  NODE_VERSION: '18'
  AZURE_WEBAPP_NAME: 'uaf-cgpa-frontend'
  CONTAINER_REGISTRY: 'uafcgparegistry'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./cgpa-calculator
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/cgpa-frontend:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.AZURE_API_URL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/cgpa-frontend:${{ github.sha }}

      - name: Configure Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group uaf-cgpa-rg \
              --linux-fx-version "DOCKER|${{ env.CONTAINER_REGISTRY }}.azurecr.io/cgpa-frontend:${{ github.sha }}"
            
            # Configure managed identity for container registry
            az webapp config container set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group uaf-cgpa-rg \
              --docker-registry-server-url https://${{ env.CONTAINER_REGISTRY }}.azurecr.io \
              --docker-registry-server-user "" \
              --docker-registry-server-password "" \
              --use-managed-identity true
